apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gep8
  namespace: user1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/scoheb/user-workload@sha256:bd6a1c34c0bf5cc6d2dac85bfdbf5bcfba8d2ede651414421587a06526053440
        name: container-image
        resources: {}
status: {}
